parameters:
    leyer.translation_addition.templating.helper.translator.class: Leyer\TranslationAdditionBundle\Templating\Helper\TranslatorHelper
    leyer.translation_addition.templating.extension.translation.class: Leyer\TranslationAdditionBundle\Templating\Twig\TranslationExtension
    leyer.translation_addition.translation.jms_updater_adapter.class: Leyer\TranslationAdditionBundle\Translation\JMSUpdaterAdapter

services:
    leyer.translation_addition.templating.helper.translator:
        class: %leyer.translation_addition.templating.helper.translator.class%
        arguments:
            - @templating.helper.translator
            - @translator
            - @router
        tags:
            - { name: templating.helper, alias: translator }

    leyer.translation_addition.templating.extension.translation:
        class: %leyer.translation_addition.templating.extension.translation.class%
        public: false
        arguments:
          - @leyer.translation_addition.templating.helper.translator
        tags:
          - { name: twig.extension }

    leyer.translation_addition.translation.jms_updater_adapter:
        class: %leyer.translation_addition.translation.jms_updater_adapter.class%
        arguments:
            - @jms_translation.updater
            - @jms_translation.config_factory
            - @jms_translation.file_writer
            - @jms_translation.loader_manager

    leyer.updater:
        alias: leyer.translation_addition.translation.jms_updater_adapter