parameters:
    leyer.translation_addition.templating.helper.translator.class: Leyer\TranslationAdditionBundle\Templating\Helper\TranslatorHelper
    leyer.translation_addition.templating.extension.translation.class: Leyer\TranslationAdditionBundle\Templating\Twig\TranslationExtension
    leyer.translation_addition.controller.translator.class: Leyer\TranslationAdditionBundle\Controller\TranslatorController

services:
    leyer.translation_addition.controller.translator:
        class: %leyer.translation_addition.controller.translator.class%
        arguments:
            - @leyer.updater

    leyer.translation_addition.templating.helper.translator:
        class: %leyer.translation_addition.templating.helper.translator.class%
        arguments:
            - @templating.helper.translator
            - @translator
            - @router
        tags:
            - { name: templating.helper, alias: translator }

    leyer.translation_addition.templating.extension.translation:
        class: %leyer.translation_addition.templating.extension.translation.class%
        public: false
        arguments:
          - @leyer.translation_addition.templating.helper.translator
        tags:
          - { name: twig.extension }